
defaults:
  - _self_
  - hydra: default
  - model: flow4D
  
slurm_id: 00000

wandb_mode: online # [offline, disabled, online]
wandb_project_name: Flow4D
dataset_path: /data/datasets/argoverse2/argoverse2/preprocess/sensor

output: ${model.name}-${slurm_id}

checkpoint: 
pretrained_weights: 
eval_only: False

# trainer
num_workers: 8
gpus: 1 # will change in code: torch.cuda.device_count()
sync_bn: true
batch_size: 8
epochs: 50
gradient_clip_val: 5.0
debug: False

version: 2024

lr: 1e-3
loss_fn: deflowLoss # choices: [ff3dLoss, zeroflowLoss, deflowLoss, weigthedflowLoss]
semantic_loss: False

# log settings
seed: 42069
log_every: 10 # steps epochs*dataset_size/batch_size
val_every: 1 # epochs
save_top_model: 10 # top_k model will be saved.

# -----> Model and Task Parameters
voxel_size: [0.2, 0.2, 0.2]
point_cloud_range: [-51.2, -51.2, -2.2, 51.2, 51.2, 4.2]
variation: 1
num_frames: 5 